[package]
name    = "libsdb_register_codegen"
version = "0.1.0"
edition = "2024"


[lib]
proc-macro = true
path = "codegen.rs"

[dependencies]
regex = "1.11.0"
proc-macro2 = "1.0.95"
syn = "2.0.100"
quote = "1.0.40"

[dependencies.nix]
version = "0.29.0"